"""empty message

Revision ID: 0d07db7f2aac
Revises: 1d9f8d812dc4
Create Date: 2023-07-13 02:01:34.401367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d07db7f2aac'
down_revision = '1d9f8d812dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gravity', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('gravity')

    # ### end Alembic commands ###
