"""empty message

Revision ID: 7d29bcf1d1c4
Revises: 5e2054257c35
Create Date: 2023-07-12 21:46:26.018492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d29bcf1d1c4'
down_revision = '5e2054257c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_characters',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_table('favorites_characters')
    op.drop_table('favorites_planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_planets',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='favorites_planets_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_planets_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'planet_id', name='favorites_planets_pkey')
    )
    op.create_table('favorites_characters',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='favorites_characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='favorites_characters_user_id_fkey')
    )
    op.drop_table('favorite_characters')
    # ### end Alembic commands ###
